2024/03/12 03:51:04 [error] 32694#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:51:08 [error] 32694#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:55:10 [error] 32694#0: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:57:53 [error] 32694#0: *99 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:57:57 [error] 32694#0: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:58:02 [error] 32694#0: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:58:06 [error] 32694#0: *98 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 03:58:15 [error] 32694#0: *111 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:10:03 [error] 32694#0: *144 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:10:40 [error] 32694#0: *162 open() "/data/server/mes-pro-vue/file/excel/基础数据-计量单位.xlsx" failed (2: No such file or directory), client: 192.168.15.70, server: 192.168.10.103, request: "GET /dobo-template/excel/%E5%9F%BA%E7%A1%80%E6%95%B0%E6%8D%AE-%E8%AE%A1%E9%87%8F%E5%8D%95%E4%BD%8D.xlsx HTTP/1.1", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:10:44 [error] 32694#0: *167 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:11:00 [error] 32694#0: *168 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:12:15 [error] 32694#0: *196 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:12:29 [error] 32694#0: *218 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:12:41 [error] 32694#0: *167 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:12:44 [error] 32694#0: *187 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.70, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:12:52 [error] 32694#0: *216 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:14:10 [error] 32694#0: *289 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:14:18 [error] 32694#0: *285 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/12 04:14:22 [error] 32694#0: *289 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "GET /dobo-equip/api/services/app/EAM_Equip_Account/ruleIsOpen HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Account/ruleIsOpen", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/03/13 01:46:41 [error] 32694#0: *2744 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.84, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCode", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/login?redirect=/"
2024/03/13 01:46:52 [error] 32694#0: *2746 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.84, server: 192.168.10.103, request: "POST /dobo-equip/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP HTTP/1.1", upstream: "http://127.0.0.1:18188/api/services/app/EAM_Equip_Classify/SearchForClassifyByNameOrCodeForUP", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/login?redirect=/"
2024/03/15 04:43:22 [error] 32694#0: *5017 directory index of "/data/server/mes-keda-test/web/MES_4.0_GWJ/dist/" is forbidden, client: 192.168.15.98, server: 192.168.10.103, request: "GET / HTTP/1.1", host: "192.168.10.103:27093"
2024/03/15 04:44:17 [error] 32694#0: *5019 directory index of "/data/server/mes-keda-test/web/MES_4.0_GWJ/dist/" is forbidden, client: 192.168.15.98, server: 192.168.10.103, request: "GET / HTTP/1.1", host: "192.168.10.103:27093"
2024/05/21 01:38:35 [error] 32694#0: *12547 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.68, server: 192.168.10.103, request: "GET /dobo-product/route/getMaterialAllEx HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/getMaterialAllEx", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/05/21 01:38:35 [error] 32694#0: *12543 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.68, server: 192.168.10.103, request: "GET /dobo-user/user/getAllUser HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-user/user/getAllUser", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/05/21 01:38:35 [error] 32694#0: *12545 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.68, server: 192.168.10.103, request: "POST /dobo-keda/order/page HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/order/page", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/05/21 01:38:35 [error] 32694#0: *12542 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.68, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/05/21 01:38:35 [error] 32694#0: *12544 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.68, server: 192.168.10.103, request: "GET /dobo-product/procedure/page?current=1&size=999&keyWord= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/procedure/page?current=1&size=999&keyWord=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:10:34 [error] 26351#0: *183 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:10:40 [error] 26351#0: *186 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:13:20 [error] 26351#0: *201 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:14:25 [error] 26351#0: *201 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:14:31 [error] 26351#0: *206 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:17:52 [error] 26351#0: *222 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:17:55 [error] 26351#0: *225 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 08:58:05 [error] 26351#0: *245 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 10:09:01 [error] 26351#0: *247 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/22 10:19:42 [error] 26351#0: *252 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/24 03:58:50 [error] 26351#0: *1255 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.186, server: 192.168.10.103, request: "POST /dobo-product/erpController/bom HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/bom", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/26 01:08:30 [error] 26351#0: *1264 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.170, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/09/26 01:08:42 [error] 26351#0: *1264 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.170, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/10/07 01:01:51 [error] 26351#0: *1849 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/10/07 01:01:51 [error] 26351#0: *1850 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/10/17 01:22:07 [error] 26351#0: *3257 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.202.162, server: 192.168.10.103, request: "GET /dobo-user/user/checkAccount?account=1004&ignoreId= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-user/user/checkAccount?account=1004&ignoreId=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/10/17 01:22:14 [error] 26351#0: *3257 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.202.162, server: 192.168.10.103, request: "GET /dobo-user/user/checkAccount?account=1004&ignoreId= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-user/user/checkAccount?account=1004&ignoreId=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/10/28 22:48:13 [error] 26351#0: *6376 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.202.215, server: 192.168.10.103, request: "POST /dobo-product/erpController/bom HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/bom", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/05 22:14:13 [error] 26351#0: *6624 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.82, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://192.168.1.124:81/"
2024/11/05 22:14:43 [error] 26351#0: *6624 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.82, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://192.168.1.124:81/"
2024/11/06 01:49:12 [error] 26351#0: *7104 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.82, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/06 01:52:05 [error] 26351#0: *7120 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.177, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/12 22:31:41 [error] 26351#0: *8368 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.75, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/12 23:44:23 [error] 26351#0: *8466 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.79, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/13 01:58:47 [error] 26351#0: *8823 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.177, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/13 01:58:47 [error] 26351#0: *8824 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.177, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/13 01:59:06 [error] 26351#0: *8830 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.75, server: 192.168.10.103, request: "GET /dobo-platform/dict/comp/listMap?menuId= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-platform/dict/comp/listMap?menuId=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/13 01:59:26 [error] 26351#0: *8831 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.75, server: 192.168.10.103, request: "GET /dobo-platform/dict/comp/listMap?menuId= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-platform/dict/comp/listMap?menuId=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/11/27 22:09:27 [error] 26351#0: *11734 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.85, server: 192.168.10.103, request: "OPTIONS /dobo-product/workCenter/selectWorkCenterList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/workCenter/selectWorkCenterList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27093/"
2024/12/06 04:57:28 [error] 26351#0: *14497 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.91, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/06 04:57:28 [error] 26351#0: *14494 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.91, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/06 04:57:41 [error] 26351#0: *14495 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.91, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/06 04:57:41 [error] 26351#0: *14492 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.91, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/06 20:35:30 [error] 26351#0: *14546 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.126, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/07 00:02:45 [error] 26351#0: *15647 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/07 00:02:51 [error] 26351#0: *15647 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/07 00:03:16 [error] 26351#0: *15651 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/07 00:03:17 [error] 26351#0: *15651 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/07 00:03:22 [error] 26351#0: *15651 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/08 20:44:00 [error] 26351#0: *15745 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/erpController/material HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/material", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/09 01:17:16 [error] 26351#0: *15980 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.177, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/login?redirect=/"
2024/12/11 03:03:21 [error] 26351#0: *17319 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 03:03:27 [error] 26351#0: *17316 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.168, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/11 03:15:00 [error] 26351#0: *17390 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 03:15:01 [error] 26351#0: *17430 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.168, server: 192.168.10.103, request: "POST /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/11 03:15:09 [error] 26351#0: *17430 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.168, server: 192.168.10.103, request: "GET /dobo-product/material/classify/listByStatus HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/classify/listByStatus", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/11 03:15:19 [error] 26351#0: *17430 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.168, server: 192.168.10.103, request: "POST /dobo-product/material/bom/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/material/bom/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/11 03:27:17 [error] 26351#0: *17508 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 03:40:17 [error] 26351#0: *17543 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 03:40:27 [error] 26351#0: *17543 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-keda/demo/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/demo/list", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 03:40:27 [error] 26351#0: *17562 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.166, server: 192.168.10.103, request: "OPTIONS /dobo-product/workCenter/selectWorkCenterList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/workCenter/selectWorkCenterList", host: "192.168.10.103:27092", referrer: "http://localhost:81/"
2024/12/11 21:02:34 [error] 26351#0: *17945 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.177, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/login?redirect=/"
2024/12/18 05:49:09 [error] 26351#0: *20064 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/18 05:49:09 [error] 26351#0: *20067 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/18 05:49:19 [error] 26351#0: *20064 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/18 05:49:19 [error] 26351#0: *20063 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.73, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/26 03:05:19 [error] 26351#0: *22045 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.71, server: 192.168.10.103, request: "GET /dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/26 03:05:22 [error] 26351#0: *22045 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.71, server: 192.168.10.103, request: "GET /dobo-product/route/selectMaxRouteName HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/selectMaxRouteName", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2024/12/26 03:05:22 [error] 26351#0: *22047 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.71, server: 192.168.10.103, request: "GET /dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/01 22:50:39 [error] 26351#0: *22340 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/01 22:50:39 [error] 26351#0: *22341 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/01 23:05:35 [error] 26351#0: *22388 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/01 23:05:35 [error] 26351#0: *22392 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.192, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/pick/proList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/pick/proList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/02 00:53:53 [error] 26351#0: *22436 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.203.89, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/02 22:42:46 [error] 26351#0: *25286 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/erpController/material HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/material", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/03 00:06:15 [error] 26351#0: *25352 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.193, server: 192.168.10.103, request: "POST /dobo-product/erpController/bom HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/bom", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/06 04:20:42 [error] 26351#0: *28567 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.188, server: 192.168.10.103, request: "POST /dobo-product/route/import HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/import", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/07 05:14:52 [error] 26351#0: *30925 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.181, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/09 01:28:01 [error] 26351#0: *33735 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.161, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/09 01:28:01 [error] 26351#0: *33737 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.161, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/09 01:28:26 [error] 26351#0: *33739 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.161, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/09 01:28:26 [error] 26351#0: *33740 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.161, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/09 02:31:28 [error] 26351#0: *33771 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.161, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:33:48 [error] 26351#0: *37028 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getBomAndRoute?id=1877527842015690753 HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getBomAndRoute?id=1877527842015690753", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:33:53 [error] 26351#0: *37028 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getBomAndRoute?id=1877527842015690753 HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getBomAndRoute?id=1877527842015690753", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:34:01 [error] 26351#0: *37028 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/plan/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:34:07 [error] 26351#0: *37028 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "GET /dobo-user/user/getAllUser HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-user/user/getAllUser", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:34:07 [error] 26351#0: *37047 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:34:07 [error] 26351#0: *37048 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "GET /dobo-product/procedure/page?current=1&size=999&keyWord= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/procedure/page?current=1&size=999&keyWord=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 00:34:07 [error] 26351#0: *37046 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-keda/order/page HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/order/page", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 03:42:04 [error] 26351#0: *37813 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.55, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/13 03:42:18 [error] 26351#0: *37813 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.55, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/14 20:27:27 [error] 26351#0: *40314 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.72, server: 192.168.10.103, request: "POST /dobo-auth/token HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-auth/token", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/15 22:35:09 [error] 26351#0: *43108 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.81, server: 192.168.10.103, request: "POST /dobo-product/erpController/material HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/material", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/15 23:03:25 [error] 26351#0: *43117 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-keda/pro/web/plan/list HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/list", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/15 23:27:22 [error] 26351#0: *43132 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.81, server: 192.168.10.103, request: "POST /dobo-product/erpController/bom HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/bom", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/16 00:13:02 [error] 26351#0: *43144 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.81, server: 192.168.10.103, request: "GET /dobo-product/procedure/page?current=1&size=999&keyWord= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/procedure/page?current=1&size=999&keyWord=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/20 01:34:24 [error] 26351#0: *46814 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.148, server: 192.168.10.103, request: "POST /dobo-product/erpController/bom HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpController/bom", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/login?redirect=/"
2025/01/21 03:58:08 [error] 26351#0: *50527 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.65, server: 192.168.10.103, request: "POST /dobo-product/workCenter/selectWorkCenterList HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/workCenter/selectWorkCenterList", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/21 05:29:19 [error] 26351#0: *51096 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.65, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/21 05:29:19 [error] 26351#0: *51095 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.65, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/22 00:03:55 [error] 26351#0: *52482 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.76, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/22 00:03:55 [error] 26351#0: *52484 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.76, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/23 10:13:51 [error] 26351#0: *54805 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.85, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/plan/getFactoryListAndShift HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/plan/getFactoryListAndShift", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/01/23 10:13:51 [error] 26351#0: *54806 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.85, server: 192.168.10.103, request: "GET /dobo-keda/pro/web/task/getRouteProcedureAll HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-keda/pro/web/task/getRouteProcedureAll", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/02/23 06:09:08 [error] 26351#0: *61607 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.60, server: 192.168.10.103, request: "GET /dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/02/23 06:20:18 [error] 26351#0: *61615 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.60, server: 192.168.10.103, request: "POST /dobo-product/route/import HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/import", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/02/24 05:46:58 [error] 26351#0: *63060 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.72, server: 192.168.10.103, request: "GET /dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy= HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/page?status=&current=1&size=15&column=&keyWord=&orderBy=", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/02/24 05:48:52 [error] 26351#0: *63060 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.72, server: 192.168.10.103, request: "POST /dobo-product/route/import HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/route/import", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/02/27 00:39:29 [error] 26351#0: *66074 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.130, server: 192.168.10.103, request: "POST /dobo-product/erpMfgOrderController/mfgOrder HTTP/1.1", upstream: "http://127.0.0.1:48000/dobo-product/erpMfgOrderController/mfgOrder", host: "192.168.10.103:27092", referrer: "http://192.168.10.103:27092/"
2025/03/12 17:43:04 [notice] 22460#0: signal process started
2025/03/12 17:53:07 [notice] 22565#0: signal process started
2025/03/12 18:07:26 [notice] 22704#0: signal process started
2025/03/12 18:13:28 [notice] 22764#0: signal process started
2025/03/12 18:15:38 [notice] 22798#0: signal process started
2025/03/12 18:16:21 [notice] 22813#0: signal process started
2025/03/14 16:22:13 [error] 22817#0: *1976 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:22:36 [error] 22817#0: *1978 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:24:16 [error] 22817#0: *1984 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:28:52 [error] 22817#0: *1988 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:28:56 [error] 22817#0: *1985 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:29:00 [error] 22817#0: *1987 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:29:10 [error] 22817#0: *1986 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /get HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:29:14 [error] 22817#0: *1989 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /getUser HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:29:18 [error] 22817#0: *1990 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:33:52 [error] 22817#0: *1992 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:34:13 [error] 22817#0: *1995 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:38:22 [error] 22817#0: *2000 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:40:55 [error] 22817#0: *2005 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:45:39 [error] 22817#0: *2011 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:45:46 [error] 22817#0: *2010 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:04 [error] 22817#0: *2009 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:05 [error] 22817#0: *2008 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:06 [error] 22817#0: *2007 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:06 [error] 22817#0: *2012 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:06 [error] 22817#0: *2013 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:46:14 [error] 22817#0: *2014 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:48:42 [error] 22817#0: *2016 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:48:43 [error] 22817#0: *2017 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 16:54:50 [notice] 20993#0: signal process started
2025/03/14 16:55:19 [error] 21008#0: *5 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 16:55:30 [error] 21008#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.134, server: 192.168.10.103, request: "GET /kanban/ HTTP/1.1", upstream: "http://127.0.0.1:3300/getTask", host: "192.168.10.103:8088"
2025/03/14 17:00:47 [error] 21008#0: *11 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:00:58 [error] 21008#0: *10 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:13:35 [error] 21008#0: *15 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:13:41 [error] 21008#0: *13 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:14:22 [error] 21008#0: *16 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:14:59 [error] 21008#0: *14 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:15:38 [error] 21008#0: *18 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 17:27:51 [error] 21008#0: *23 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:28:06 [error] 21008#0: *24 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:28:12 [error] 21008#0: *21 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088"
2025/03/14 17:40:32 [notice] 21562#0: signal process started
2025/03/14 17:40:42 [error] 21565#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", upstream: "http://192.168.10.103:3300/api/getTask", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:42:13 [error] 21565#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/ HTTP/1.1", upstream: "http://192.168.10.103:3300/api/", host: "192.168.10.103:8088"
2025/03/14 17:47:50 [notice] 21648#0: signal process started
2025/03/14 17:49:03 [notice] 21670#0: signal process started
2025/03/14 17:49:17 [error] 21673#0: *4 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:55:52 [error] 21673#0: *9 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:59:33 [error] 21673#0: *11 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 17:59:45 [error] 21673#0: *15 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 18:05:40 [error] 21673#0: *19 could not find named location "@router", client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
2025/03/14 18:16:28 [notice] 21988#0: signal process started
2025/03/14 18:16:54 [error] 21992#0: *2 open() "/data/server/mes-keda-test/web/MES_temporary_kanban/dist/api/getTask" failed (2: No such file or directory), client: 192.168.15.134, server: 192.168.10.103, request: "GET /api/getTask HTTP/1.1", host: "192.168.10.103:8088", referrer: "http://192.168.10.103:8088/"
